### ISSUE TITLE
How do you safely upgrade PoisonTap?

### ISSUE THREAD

**Issue by victorhooi** [samyk/poisontap#94]
Sorry if this has already been asked, but how do you *safely* upgrade PoisonTap without being infected?

I have a USBArmory and a LAN Turtle I'm hoping to use to play around with and test PoisonTap with.

However, how do I plug in and upgrade PoisonTap itself, without having my main machine be infected?

And for my dummy machines - is there anyway to wipe PoisonTap and start from a clean slate - short of re-installing the machine?

**Comment by samyk** [comment]
Clear your cache to clean a machine. However, if PoisonTap has stolen any cookies, those cookies are still valid and you need to log out of all of those websites (assuming the website actually invalidates the cookie instead of just removing it from the user's browser).

To work with PoisonTap, exit any browsers, then you can safely connect it to your machine.
